app = 'sgummalla-net-staging'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
